name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test_2004:
    name: Ubuntu 20.04 - Python ${{ matrix.python }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.5.10", "3.6.15"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install --upgrade pip
      - name: Install reloading
        run: pip install ".[development]"
      - name: Lint with flake8
        run: flake8
      - name: Type check with pyright
        run: pyright
      - name: Test with unittest
        run: python -m unittest
  test_2204:
    name: Ubuntu 22.04 - Python ${{ matrix.python }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.7.17", "3.8.18", "3.9.20", "3.10.15", "3.11.11", "3.12.8", "3.13.1"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install --upgrade pip
      - name: Install reloading
        run: pip install ".[development]"
      - name: Lint with flake8
        run: flake8
      - name: Type check with pyright
        run: pyright
      - name: Test with unittest
        run: python -m unittest
